# Generated by Django 2.0.2 on 2020-02-09 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaña', '0001_initial'),
        ('distrito', '0001_initial'),
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.TextField()),
                ('campaña', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaña.Campaña')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='departamento.Departamento')),
                ('distrito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='distrito.Distrito')),
            ],
        ),
    ]
